### ISSUE TITLE
Makefile:159: recipe for target 'install' failed

### ISSUE THREAD

**Issue by thatreguy** [airbus-seclab/crashos#3]
After doing make, when I do make install it fails. When I checked the tools/installer_vmware.sh file:
VMNAME="crashos"
VMPATH="/home/anais/Vmware/${VMNAME}"
VMDISK="${VMPATH}/${VMNAME}.vmdk"
VMMNT="${VMPATH}/mnt"

All these paths are local! Also vmdk does not exist.
All I can see in my build dir is:
linker.lds  test.bin

Please help booting this image with VMWare.

Thanks!

**Comment by thatreguy** [comment]
I'd like to add that I got it running in qemu but not VMware.

~/crashos$ sudo qemu-system-x86_64 -serial mon:stdio -kernel build/test.bin
VNC server running on 127.0.0.1:5900
test_lgdt    :  OK
test_lldt    :  OK
test_ltr     :  OK
test_lidt    :  OK
test_mov_cr3 :  OK
test_lmsw    :  OK
test_clts    :  OK
test_mov_drx :  OK
test_invd    :  OK
test_wbinvd  :  OK
test_invlpg  :  OK
test_hlt     :  OK
test_rdmsr   :  OK
test_wrmsr   :  OK
test_rdpmc   : Default Handler : IT/EXCP 6 at eip 0x201fa7

**Comment by sduverger** [comment]
Hi,

Thanks for giving it a try. We never intended to provide VMware VM disk
image as we didn't want to tie the project to a specific hypervisor.
But actually i think it's worth it. VMDK is proprietary, but a lot of tools
are able to understand its format and convert it.

You can easily build one. The "installer" script is just an illustration to
what can be done with an existing one.
However you will still need vmware-disktools (present in
Workstation/Fusion, not sure for Player) to be able to mount your local
VMDK.
Notice that your virtual disk should have Grub installed as bootloader and
configured to boot "crash OS" which is multiboot compliant.

Booting with Qemu is easier because it supports loading ELF kernel directly
without the need for a virtual disk and a bootloader.

I'll fix the issue ASAP and provide a small "vmdk" image.

**Comment by sduverger** [comment]
fixed by 3e28430a4e926e0bc368f9f85768bd84f1918ebc
